spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.mms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            pcout.producer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            pcout.producer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
            pcin.consumer.key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            pcin.consumer.value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
      bindings:
        pvout.destination: pvs
        pvout.producer.header-mode: raw
        pvin.destination: pvs
        pvout.consumer.header-mode: raw
        pcout.destination: pcs
        pcout.producer.use-native-encoding: true
        pcin.destination: pcs
        pcin.consumer.use-native-encoding: true
        pcin.group: pcs
        pcin.content-type: application/json
        pcin.consumer.header-mode: raw




